apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service-deployment
  labels:
    app: backend-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - name: backend-service
          image: ductruong194/backend-service
          ports:
            - containerPort: 3000